# Build Docker image using Azure Pipelines
# Target: Azure Container Registry (ACR)

# source branch trigger  : branch called LogNook\AppInsights is logging to Azure Application Insights (master branch has log-to-sql table functionality)
trigger:
- AppInsights

pool:
  vmImage: 'win1803'

variables:
  buildConfiguration: 'Release'
  imageName: 'lognook:$(build.buildId)'

steps:
- script:  |
    docker build -f ./CCA.Services.LogNook/Dockerfile -t nooksandcrannies.azurecr.io/$(imageName) .
    az acr login --name NooksAndCrannies
    docker push nooksandcrannies.azurecr.io/$(imageName)

